### ISSUE TITLE
Example cannot be compiled successfully.

### ISSUE THREAD

**Issue by SmartDesigner** [DistributedClocks/CVector#5]
I cloned CVector and compiled example. I failed because the option -std=c11 are not included. I added the option explicitly and tried again. This time I failed linking because undefined reference to functions like `clock_init'.
My environment is Ubuntu 16.04, gcc 4.9.

**Comment by fruffy** [comment]
Hi SmartDesigner,
have you tried compiling the examples from the top level directory? The makefile in the example folder is incomplete and will be called by the makefile in the root folder. It may be that the test framework is not compatible with your current version of Ubuntu, which is a current todo to fix. I disabled the tests for now and updated the makefile. Does it compile for you?
